---
project:
  name:
    type: "string"
    required: true
    maxLength: 100
    unique: true
  description:
    type: "string"
  priority:
    type: "boolean"
    defaultsTo: false
  shortLink:
      unique: true
      maxLength: 8
      required: true